name: Store submission on release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write

jobs:

  microsoft_store:
    name: Publish Microsoft Store
    environment: store
    runs-on: ubuntu-latest
    steps:
      - name: BODGY - Set up Gnome Keyring for future Cert Auth
        run: |-
          sudo apt-get install -y gnome-keyring
          export $(dbus-launch --sh-syntax)
          export $(echo 'anypass_just_to_unlock' | gnome-keyring-daemon --unlock)
          export $(echo 'anypass_just_to_unlock' | gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Get latest URL from public releases
        id: releaseVars
        run: |
          release=$(curl https://api.github.com/repos/Microsoft/PowerToys/releases | jq '[.[]|select(.name | contains("Release"))][0]')
          assets=$(jq -n "$release" | jq '.assets')
          powerToysSetup=$(jq -n "$assets" | jq '[.[]|select(.name | contains("PowerToysUserSetup"))]')
          echo powerToysInstallerX64Url=$(jq -n "$powerToysSetup" | jq -r '[.[]|select(.name | contains("x64"))][0].browser_download_url') >> $GITHUB_OUTPUT
          echo powerToysInstallerArm64Url=$(jq -n "$powerToysSetup" | jq -r '[.[]|select(.name | contains("arm64"))][0].browser_download_url') >> $GITHUB_OUTPUT

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - uses: microsoft/setup-msstore-cli@v1.1

      - name: Test .Net 9.0
        run: |-
          dotnet --info
